packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - workerd

allowBuilds:
  esbuild: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260907.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260907.1'
  - '@cloudflare/workerd-linux-64@1.20260907.1'
  - '@cloudflare/workerd-linux-arm64@1.20260907.1'
  - '@cloudflare/workerd-windows-64@1.20260907.1'
  - miniflare@5.20260907.0-alpha
  - workerd@1.20260907.1
  - wrangler@4.129.1
