import { useEffect, useMemo, useState, type ReactNode } from "react";
import { DEFAULT_GLOSSARY_ENTRIES, type AssetClass, type MetricState } from "@stonks/contracts";
import type { ChartDto, DashboardApi, InstrumentDto, MetricValueDto, MomentumBreakdownDto, ResultMatchDto, ScreenResultsDto } from "./api";
import { TermPopover } from "./learn";

const assetLabel: Record<AssetClass, string> = { equity: "NSE equity", etf: "NSE ETF", mutual_fund: "AMFI mutual fund" };
const percentMetrics = new Set(["return_1d", "return_1w", "return_1m", "return_3m", "return_6m", "return_12m", "volatility_1y", "max_drawdown_1y", "benchmark_rs_3m", "benchmark_rs_6m", "benchmark_rs_12m"]);
const unitForMetric = (metric: string): string | undefined => percentMetrics.has(metric) ? "percent" : undefined;
const glossaryForMetric = (metric: string) => {
  const slug = metric.startsWith("return_") ? "return" : metric === "volume" ? "volume" : metric === "volume_1w_avg" ? "average-volume" : metric === "market_cap" ? "market-cap" : metric === "rs_rating" ? "relative-strength-rating" : metric === "volatility_1y" ? "volatility" : metric === "max_drawdown_1y" ? "drawdown" : metric === "benchmark_rs_3m" || metric === "benchmark_rs_6m" || metric === "benchmark_rs_12m" ? "relative-strength-benchmark" : undefined;
  return slug ? DEFAULT_GLOSSARY_ENTRIES.find((entry) => entry.slug === slug) : undefined;
};
function MetricTerm({ metric, children }: { readonly metric: string; readonly children: ReactNode }) { const entry = glossaryForMetric(metric); return entry ? <TermPopover entry={entry}>{children}</TermPopover> : children; }
const formatNumber = (value: number, unit?: string): string => {
  const displayValue = unit === "percent" && Math.abs(value) <= 1 ? value * 100 : value;
  const formatted = new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(displayValue);
  return unit === "percent" ? `${formatted}%` : unit === "currency" ? `₹${formatted}` : formatted;
};

type MetricValueInput = Omit<MetricValueDto, "value"> & { readonly value?: number | null };
export function MetricValue({ value, unit, label }: { readonly value: MetricValueInput; readonly unit?: string | undefined; readonly label?: string | undefined }) {
  const stateLabel: Record<MetricState, string> = { present: typeof value.value === "number" && Number.isFinite(value.value) ? formatNumber(value.value, unit) : "Missing data", missing: "Missing data", not_applicable: "Not applicable" };
  const text = stateLabel[value.state];
  return <span className={`metric-value metric-${value.state}`} aria-label={label ? `${label}: ${text}` : text} data-state={value.state}>{text}</span>;
}

export function MomentumBreakdown({ momentum }: { readonly momentum: MomentumBreakdownDto }) {
  return <section className="momentum-breakdown" aria-labelledby="momentum-breakdown-title"><div className="section-heading"><div><p className="eyebrow">EXPLAINABLE SCORE</p><h2 id="momentum-breakdown-title">Momentum breakdown</h2></div><span className="coverage-badge">{Math.round(momentum.coverage * 100)}% coverage</span></div>{momentum.warning ? <p className="data-warning" role="status">{momentum.warning}</p> : null}<div className="table-wrap"><table className="data-table momentum-table"><caption>Normalized values are 0–1; contribution is normalized × weight.</caption><thead><tr><th scope="col">Component</th><th scope="col">Raw value</th><th scope="col">Normalized (0–1)</th><th scope="col">Weight</th><th scope="col">Contribution</th></tr></thead><tbody>{momentum.components.map((component) => <tr key={component.componentId}><th scope="row">{component.label}</th><td>{component.raw === null ? <MetricValue value={{ value: null, state: "missing" }} /> : formatNumber(component.raw, component.unit)}</td><td>{component.normalized === null ? <MetricValue value={{ value: null, state: "missing" }} /> : formatNumber(component.normalized)}</td><td>{formatNumber(component.weight * 100)}%</td><td>{component.contribution === null ? <MetricValue value={{ value: null, state: "missing" }} /> : formatNumber(component.contribution)}</td></tr>)}</tbody></table></div><dl className="breakdown-meta"><div><dt>Cohort</dt><dd>{momentum.cohort}</dd></div><div><dt>Formula</dt><dd>{momentum.formulaVersion}</dd></div><div><dt>Source date</dt><dd>{momentum.sourceDate ?? "—"}</dd></div></dl></section>;
}

export function ResultsTable({ matches, instruments, limit, offset, total, onPage, onOpen, sort, direction, onSort }: { readonly matches: readonly ResultMatchDto[]; readonly instruments: readonly InstrumentDto[]; readonly limit: number; readonly offset: number; readonly total: number; readonly onPage: (offset: number) => void; readonly onOpen?: (instrumentId: string) => void; readonly sort?: "rank" | "score" | "symbol"; readonly direction?: "ascending" | "descending"; readonly onSort?: (sort: "rank" | "score" | "symbol", direction: "ascending" | "descending") => void }) {
  const [localSort, setLocalSort] = useState<"rank" | "score" | "symbol">("rank");
  const [localDirection, setLocalDirection] = useState<"ascending" | "descending">("ascending");
  const activeSort = sort ?? localSort;
  const activeDirection = direction ?? localDirection;
  const byId = useMemo(() => new Map(instruments.map((instrument) => [instrument.instrumentId, instrument])), [instruments]);
  const sorted = useMemo(() => [...matches].sort((left, right) => { const a = activeSort === "symbol" ? byId.get(left.instrumentId)?.symbol ?? left.symbol ?? "" : activeSort === "rank" ? left.rank : left.score ?? -Infinity; const b = activeSort === "symbol" ? byId.get(right.instrumentId)?.symbol ?? right.symbol ?? "" : activeSort === "rank" ? right.rank : right.score ?? -Infinity; const result = typeof a === "string" ? a.localeCompare(String(b)) : Number(a) - Number(b); return activeDirection === "ascending" ? result : -result; }), [activeDirection, activeSort, byId, matches]);
  const ordered = onSort ? matches : sorted;
  const changeSort = (next: "rank" | "score" | "symbol") => { const nextDirection = activeSort === next ? (activeDirection === "ascending" ? "descending" : "ascending") : next === "score" ? "descending" : "ascending"; if (onSort) onSort(next, nextDirection); else { setLocalSort(next); setLocalDirection(nextDirection); } };
  const lastPage = offset + limit >= total;
  return <div className="results-table-region"><div className="table-wrap"><table className="data-table" aria-label="Screen results"><thead><tr><th scope="col"><button className="table-sort" aria-sort={activeSort === "rank" ? activeDirection : "none"} onClick={() => changeSort("rank")}>Rank</button></th><th scope="col"><button className="table-sort" aria-sort={activeSort === "symbol" ? activeDirection : "none"} onClick={() => changeSort("symbol")}>Instrument</button></th><th scope="col">Asset class</th><th scope="col"><button className="table-sort" aria-label="Sort by score" aria-sort={activeSort === "score" ? activeDirection : "none"} onClick={() => changeSort("score")}><MetricTerm metric="rs_rating">Momentum score</MetricTerm></button></th><th scope="col">Why it matched</th></tr></thead><tbody>{ordered.length ? ordered.map((match) => { const instrument = byId.get(match.instrumentId); const symbol = instrument?.symbol ?? match.symbol ?? match.instrumentId; const instrumentHref = `/instruments/${encodeURIComponent(match.instrumentId)}`; return <tr key={match.instrumentId}><td>{match.exited ? "Exited" : match.rank}</td><th scope="row">{onOpen ? <a className="table-link" href={instrumentHref} onClick={(event) => { event.preventDefault(); onOpen(match.instrumentId); }} aria-label={match.rank === 1 ? "View first match research" : `View ${symbol} research`}>{symbol}</a> : <span>{symbol}</span>}{instrument?.name ?? match.name ? <small>{instrument?.name ?? match.name}</small> : null}</th><td>{assetLabel[instrument?.assetClass ?? match.assetClass ?? "equity"]}</td><td>{match.score === null ? <MetricValue value={{ value: null, state: "missing" }} /> : formatNumber(match.score)}</td><td><span>{match.explanation?.text ?? "Match recorded"}</span>{match.entered ? <span className="result-flag">Entered this run</span> : null}{match.explanation?.clauses?.length ? <details><summary>Explain clause</summary><ul className="clause-list">{match.explanation.clauses.map((clause) => <li key={clause.clause}><strong>{clause.result}</strong> · {clause.clause}{clause.value ? <> — <MetricValue value={clause.value} unit={clause.metric ? unitForMetric(clause.metric) : undefined} /></> : null}</li>)}</ul></details> : null}</td></tr>; }) : <tr><td colSpan={5}>No matches in this run.</td></tr>}</tbody></table></div><div className="pagination" aria-label="Results pagination"><span>Showing {total ? offset + 1 : 0}–{Math.min(offset + limit, total)} of {total}</span><button className="button button-quiet small" onClick={() => onPage(Math.max(0, offset - limit))} disabled={offset === 0}>Previous page</button><button className="button button-quiet small" onClick={() => onPage(offset + limit)} disabled={lastPage} aria-label="Next page">Next page</button></div></div>;
}

export function ComparisonTable({ instruments }: { readonly instruments: readonly InstrumentDto[] }) {
  const classes = new Set(instruments.map((instrument) => instrument.assetClass));
  const incomparable = classes.size > 1;
  const metricNames = [...new Set(instruments.flatMap((instrument) => instrument.metricRows?.map((row) => row.metric) ?? []))];
  const metric = (instrument: InstrumentDto, name: string): MetricValueDto => instrument.metricRows?.find((row) => row.metric === name) ?? { value: null, state: "missing" };
  return <section className="comparison" aria-labelledby="comparison-title"><div className="section-heading"><div><p className="eyebrow">SIDE BY SIDE</p><h2 id="comparison-title">Compare instruments</h2></div></div>{incomparable ? <p className="data-warning" role="note">These instruments are <strong>not directly comparable</strong> across asset classes. Values retain their source units and definitions.</p> : null}<div className="table-wrap"><table className="data-table" aria-label="Instrument comparison"><thead><tr><th scope="col">Metric</th>{instruments.map((instrument) => <th scope="col" key={instrument.instrumentId}>{instrument.symbol ?? instrument.instrumentId}<small>{assetLabel[instrument.assetClass]}</small></th>)}</tr></thead><tbody>{<tr><th scope="row">Asset class</th>{instruments.map((instrument) => <td key={instrument.instrumentId}>{assetLabel[instrument.assetClass]}</td>)}</tr>}{metricNames.map((name) => <tr key={name}><th scope="row"><MetricTerm metric={name}>{name}</MetricTerm></th>{instruments.map((instrument) => <td key={instrument.instrumentId}><MetricValue value={metric(instrument, name)} unit={unitForMetric(name)} /></td>)}</tr>)}</tbody></table></div></section>;
}

function PriceChart({ chart, valueLabel }: { readonly chart: ChartDto; readonly valueLabel: string }) {
  const points = chart.points.filter((point) => point.value !== null);
  const values = points.map((point) => point.value!);
  const min = Math.min(...values, 0); const max = Math.max(...values, 1); const range = max - min || 1;
  const path = points.map((point, index) => `${(index / Math.max(1, points.length - 1)) * 100},${100 - ((point.value! - min) / range) * 100}`).join(" ");
  return <section aria-labelledby="history-title" className="chart-section"><div className="section-heading"><div><p className="eyebrow">THREE-YEAR HISTORY</p><h2 id="history-title">{valueLabel} history</h2></div><span className="section-note">Adjusted, daily observations</span></div>{points.length > 1 ? <svg className="line-chart" viewBox="0 0 100 100" role="img" aria-label={`${valueLabel} time series with ${points.length} observations`} preserveAspectRatio="none"><polyline points={path} fill="none" stroke="currentColor" strokeWidth="1.5" vectorEffect="non-scaling-stroke" /></svg> : <p className="empty-card">Not enough observations to draw a trend.</p>}<div className="table-wrap"><table className="data-table history-table" aria-label="History data"><thead><tr><th scope="col">Date</th><th scope="col">{valueLabel}</th></tr></thead><tbody>{chart.points.map((point) => <tr key={point.date}><th scope="row">{point.date}</th><td>{point.value === null ? <MetricValue value={{ value: null, state: "missing" }} /> : formatNumber(point.value)}</td></tr>)}</tbody></table></div></section>;
}

export function InstrumentResearch({ instrument, chart }: { readonly instrument: InstrumentDto; readonly chart?: ChartDto | null }) {
  const valueLabel = instrument.assetClass === "mutual_fund" ? "Adjusted NAV" : "Adjusted price";
  const detailTitle = instrument.assetClass === "equity" ? "Share fundamentals" : instrument.assetClass === "etf" ? "ETF metadata" : "Fund category and risk";
  const detailCopy = instrument.assetClass === "equity" ? "Revenue, profitability, balance-sheet, cash-flow, valuation, and corporate-action fields are shown when officially filed." : instrument.assetClass === "etf" ? "Exchange-traded momentum, drawdown, volatility, and tracking metadata are shown when officially published." : "Category-relative returns, volatility, and drawdown are shown for mutual funds; exchange volume is not applicable.";
  const rowFor = (name: string): MetricValueDto => instrument.metricRows?.find((row) => row.metric === name) ?? { value: null, state: "missing" };
  const fallbackMomentum: MomentumBreakdownDto = { components: [], cohort: assetLabel[instrument.assetClass], formulaVersion: "momentum-v2-cohort", coverage: 0, sourceDate: instrument.metricRows?.find((row) => row.effectiveDate)?.effectiveDate ?? null, warning: "Momentum component detail is unavailable for this instrument." };
  const assetDetail = <AssetDetail instrument={instrument} rowFor={rowFor} />;
  return <section className="instrument-research" aria-labelledby="instrument-title"><div className="hero-row"><div><p className="eyebrow">{assetLabel[instrument.assetClass].toUpperCase()} / RESEARCH</p><h1 id="instrument-title">{instrument.name ?? instrument.symbol ?? instrument.instrumentId} research</h1><p className="lede">{instrument.symbol ?? instrument.instrumentId} · {assetLabel[instrument.assetClass]}</p></div><span className="active-badge">{instrument.active ? "Active instrument" : "Historical instrument"}</span></div>{chart ? <PriceChart chart={chart} valueLabel={valueLabel} /> : <div className="empty-card">History is unavailable for this instrument.</div>}<MomentumBreakdown momentum={instrument.momentum ?? fallbackMomentum} /><section className="metric-panel" aria-labelledby="metrics-title"><div className="section-heading"><div><p className="eyebrow">CURRENT SNAPSHOT</p><h2 id="metrics-title">Metrics and data quality</h2></div></div><div className="metric-cards">{(instrument.metricRows ?? []).map((row) => <article className="metric-card" key={row.metric}><span className="context-label"><MetricTerm metric={row.metric}>{row.metric}</MetricTerm></span><MetricValue value={row} unit={unitForMetric(row.metric)} /></article>)}</div></section><section className="benchmark-panel" aria-labelledby="benchmark-title"><p className="eyebrow">RELATIVE PERFORMANCE</p><h2 id="benchmark-title">Benchmark comparison</h2><div className="metric-cards"><article className="metric-card"><span className="context-label"><MetricTerm metric="benchmark_rs_3m">3-month benchmark RS</MetricTerm></span><MetricValue value={rowFor("benchmark_rs_3m")} unit="percent" /></article><article className="metric-card"><span className="context-label"><MetricTerm metric="benchmark_rs_6m">6-month benchmark RS</MetricTerm></span><MetricValue value={rowFor("benchmark_rs_6m")} unit="percent" /></article><article className="metric-card"><span className="context-label"><MetricTerm metric="benchmark_rs_12m">12-month benchmark RS</MetricTerm></span><MetricValue value={rowFor("benchmark_rs_12m")} unit="percent" /></article></div></section><section className="asset-detail" aria-labelledby="asset-detail-title"><p className="eyebrow">ASSET-SPECIFIC RESEARCH</p><h2 id="asset-detail-title">{detailTitle}</h2><p className="research-note">{detailCopy}</p>{assetDetail}{instrument.metadata && Object.keys(instrument.metadata).length ? <dl className="breakdown-meta">{Object.entries(instrument.metadata).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value ?? "—"}</dd></div>)}</dl> : null}</section></section>;
}

function AssetDetail({ instrument, rowFor }: { readonly instrument: InstrumentDto; readonly rowFor: (name: string) => MetricValueDto }) {
  if (instrument.assetClass === "equity") return <><h3>Fundamental periods</h3>{instrument.fundamentalPeriods?.length ? <div className="table-wrap"><table className="data-table"><caption className="sr-only">Filed fundamental periods</caption><thead><tr><th scope="col">Period end</th><th scope="col">Period type</th><th scope="col">Filed</th><th scope="col">Metrics</th></tr></thead><tbody>{instrument.fundamentalPeriods.map((period) => <tr key={period.periodId}><th scope="row">{period.periodEnd}</th><td>{period.periodType}</td><td>{period.filedAt}</td><td>{Object.entries(period.metrics).map(([key, value]) => <span className="detail-chip" key={key}>{key}: {String(value)}</span>)}</td></tr>)}</tbody></table></div> : <p className="data-warning">Fundamental periods: unavailable.</p>}<h3>Corporate actions</h3>{instrument.corporateActions?.length ? <ul className="detail-list">{instrument.corporateActions.map((action) => <li key={action.actionId}><strong>{action.actionDate}</strong> · {action.actionType}</li>)}</ul> : <p className="data-warning">Corporate actions: unavailable.</p>}</>;
  if (instrument.assetClass === "etf") return <div className="metric-cards"><article className="metric-card"><span className="context-label">Tracking difference</span><MetricValue value={rowFor("tracking_difference")} unit="percent" /></article><article className="metric-card"><span className="context-label">1-year volatility</span><MetricValue value={rowFor("volatility_1y")} unit="percent" /></article><article className="metric-card"><span className="context-label">1-year drawdown</span><MetricValue value={rowFor("max_drawdown_1y")} unit="percent" /></article></div>;
  return <div className="metric-cards"><article className="metric-card"><span className="context-label">Category</span><span className="metric-value">{instrument.metadata?.category ?? "Not available"}</span></article><article className="metric-card"><span className="context-label">Category rank</span><MetricValue value={rowFor("category_rank")} /></article><article className="metric-card"><span className="context-label">Risk / volatility</span><MetricValue value={rowFor("volatility_1y")} unit="percent" /></article><article className="metric-card"><span className="context-label">Exchange volume</span><MetricValue value={{ value: null, state: "not_applicable" }} /></article></div>;
}

export function ScreenResultsView({ screenId, api, onBack, onOpenInstrument }: { readonly screenId: string; readonly api: DashboardApi; readonly onBack: () => void; readonly onOpenInstrument: (instrumentId: string) => void }) {
  const [result, setResult] = useState<ScreenResultsDto | null>(null);
  const [instruments, setInstruments] = useState<InstrumentDto[]>([]);
  const [offset, setOffset] = useState(0);
  const [sort, setSort] = useState<"rank" | "score" | "symbol">("rank");
  const [direction, setDirection] = useState<"ascending" | "descending">("ascending");
  const [error, setError] = useState<string | null>(null);
  const [attempt, setAttempt] = useState(0);
  const [running, setRunning] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  useEffect(() => { let active = true; setError(null); if (!api.getResults) { setError("Results are unavailable in this client."); return undefined; } void api.getResults(screenId, { offset, limit: 25, sort, direction: direction === "ascending" ? "asc" : "desc" }).then(async (next) => { if (!active) return; setResult(next); if (api.getInstrument) { const details = await Promise.all(next.run.matches.map((match) => api.getInstrument!(match.instrumentId).catch(() => null))); if (active) setInstruments(details.filter((item): item is InstrumentDto => item !== null)); } }).catch(() => { if (active) setError("Unable to load screen results. Retry to continue."); }); return () => { active = false; }; }, [api, attempt, direction, offset, screenId, sort]);
  if (error) return <section className="research-view"><button className="back-link" onClick={onBack}>← Overview</button><div className="error-banner" role="alert">{error}<button className="button button-quiet small" onClick={() => setAttempt((value) => value + 1)}>Retry</button></div></section>;
  if (!result) return <section className="research-view"><p className="loading-card" aria-live="polite">Loading screen results…</p></section>;
  const firstMomentum = result.run.matches.find((match) => match.momentum)?.momentum;
  const runNow = async () => { if (!api.runScreen) return; setRunning(true); setError(null); try { await api.runScreen(result.screen.id); setAttempt((value) => value + 1); } catch { setError("Unable to run this screen. Retry to continue."); } finally { setRunning(false); } };
  const changeServerSort = (next: "rank" | "score" | "symbol", nextDirection: "ascending" | "descending") => { setSort(next); setDirection(nextDirection); setOffset(0); };
  return <section className="research-view" aria-labelledby="results-title"><button className="back-link" onClick={onBack}>← Overview</button><div className="hero-row"><div><p className="eyebrow">SCREEN RESULTS / {result.run.effectiveDate}</p><h1 id="results-title">{result.screen.name} results</h1><p className="lede">{result.run.matchCount} top matches · mechanical filter: <code>{result.screen.source}</code></p></div><div className="editor-actions"><button className="button button-primary" onClick={() => void runNow()} disabled={running}>{running ? "Running…" : "Run screen"}</button><button className="button button-secondary" onClick={() => setSelected(new Set(result.run.matches.map((match) => match.instrumentId)))}>Select all</button></div></div><ResultsTable matches={result.run.matches} instruments={instruments} limit={result.pagination.limit} offset={result.pagination.offset} total={result.pagination.total} sort={sort} direction={direction} onSort={changeServerSort} onPage={setOffset} onOpen={onOpenInstrument} />{firstMomentum ? <MomentumBreakdown momentum={firstMomentum} /> : null}<section className="comparison-block"><div className="section-heading"><div><p className="eyebrow">OPTIONAL COMPARISON</p><h2>Compare selected</h2></div><span className="section-note">{selected.size} selected</span></div><div className="selection-list">{result.run.matches.slice(0, 10).map((match) => <label key={match.instrumentId}><input type="checkbox" checked={selected.has(match.instrumentId)} onChange={(event) => setSelected((current) => { const next = new Set(current); if (event.target.checked) next.add(match.instrumentId); else next.delete(match.instrumentId); return next; })} /> {match.symbol ?? match.instrumentId}</label>)}</div>{selected.size > 1 ? <ComparisonTable instruments={instruments.filter((instrument) => selected.has(instrument.instrumentId))} /> : null}</section></section>;
}

export function InstrumentView({ instrumentId, api, onBack }: { readonly instrumentId: string; readonly api: DashboardApi; readonly onBack: () => void }) {
  const [instrument, setInstrument] = useState<InstrumentDto | null>(null);
  const [chart, setChart] = useState<ChartDto | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [attempt, setAttempt] = useState(0);
  useEffect(() => { let active = true; if (!api.getInstrument) { setError("Instrument research is unavailable in this client."); return undefined; } void api.getInstrument(instrumentId).then(async (next) => { if (!active) return; setInstrument(next); if (api.getChart) { try { setChart(await api.getChart(instrumentId)); } catch { setChart(null); } } }).catch(() => { if (active) setError("Unable to load this instrument. Retry to continue."); }); return () => { active = false; }; }, [api, attempt, instrumentId]);
  return <section className="research-view"><button className="back-link" onClick={onBack}>← Results</button>{error ? <div className="error-banner" role="alert">{error}<button className="button button-quiet small" onClick={() => setAttempt((value) => value + 1)}>Retry</button></div> : instrument ? <InstrumentResearch instrument={instrument} chart={chart} /> : <p className="loading-card" aria-live="polite">Loading instrument research…</p>}</section>;
}
